FROM selenium/standalone-chrome-debug
#nkovacs/selenium-standalone-phantomjs
# selenium/standalone-chrome

LABEL maintainer="Cohen Harvey <cohen.n.harvey@gmail.com>"

RUN x11vnc -storepasswd password /home/seluser/.vnc/passwd
